<?php

namespace backend\models;

use common\models\myFuncs;
use Yii;

/**
 * This is the model class for table "{{%hanghoa}}".
 *
 * @property integer $id
 * @property string $ma
 * @property string $name
 * @property integer $nhomloaihang_id
 * @property string $hinhanh
 * @property string $code
 *
 * @property Anhhanghoa[] $anhhanghoas
 * @property Nhomloaihang $nhomloaihang
 * @property Quydoidonvitinh[] $quydoidonvitinhs
 */
class Hanghoa extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%hanghoa}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nhomloaihang_id'], 'required'],
            [['ma'], 'string', 'max' => 45],
            [['name', 'hinhanh', 'code', 'nhomloaihang_id'], 'string', 'max' => 100],
//            [['nhomloaihang_id'], 'exist', 'skipOnError' => true, 'targetClass' => Nhomloaihang::className(), 'targetAttribute' => ['nhomloaihang_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ma' => 'Mã hàng',
            'name' => 'Tên hàng',
            'nhomloaihang_id' => 'Nhóm',
            'hinhanh' => 'Hình đại diện',
            'code' => 'Code',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnhhanghoas()
    {
        return $this->hasMany(Anhhanghoa::className(), ['hanghoa_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNhomloaihang()
    {
        return $this->hasOne(Nhomloaihang::className(), ['id' => 'nhomloaihang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuydoidonvitinhs()
    {
        return $this->hasMany(Quydoidonvitinh::className(), ['hanghoa_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->code = myFuncs::createCode($this->name);

        $this->nhomloaihang_id = myFuncs::getIdOtherModel($this->nhomloaihang_id, $nhom = new Nhomloaihang());
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
//        $qddvts = Quydoidonvitinh::findAll(['hanghoa_id' => $this->id]);
//        foreach ($qddvts as $qddvt) {
//            $qddvt->delete();
//        }
//        if(isset($_POST['Quydoidonvitinh'])){
//            /** @var  $quydoidvt Quydoidonvitinh */
//            foreach ($_POST['Quydoidonvitinh'] as $item) {
//                $quydoidvt = new Quydoidonvitinh();
//                $quydoidvt->attributes = $item;
//                $quydoidvt->hanghoa_id = $this->id;
//                $quydoidvt->save();
//            }
//        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
