<?php

namespace backend\models;

use common\models\myFuncs;
use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%muabanhang}}".
 *
 * @property integer $id
 * @property string $type
 * @property string $ngaygiaodich
 * @property integer $nhacungcap_khachhang_id
 * @property string $maphieu
 * @property string $dienthoai
 * @property string $sohoadonVAT
 * @property string $sophieunhaptay
 * @property string $diachi
 * @property string $ghichu
 * @property string $ngaygiao
 * @property string $kieuthanhtoan
 * @property string $hinhthucthanhtoan
 * @property string $hanthanhtoan
 * @property integer $nhanviengiaodich
 * @property integer $chietkhau
 * @property bool $nhapdauky
 *
 * @property Chitietmuaban[] $chitietmuabans
 * @property NhacungcapKhachhang $nhacungcapKhachhang
 * @property User $nhanviengiaodich0
 * @property Thanhtoan[] $thanhtoans
 */
class Muabanhang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%muabanhang}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kieuthanhtoan', 'hinhthucthanhtoan','maphieu'], 'required'],
            [['type', 'ghichu', 'kieuthanhtoan', 'hinhthucthanhtoan','nhacungcap_khachhang_id'], 'string'],
            [['ngaygiaodich', 'ngaygiao', 'hanthanhtoan','nhapdauky','nhacungcap_khachhang_id'], 'safe'],
            [['nhanviengiaodich', 'chietkhau'], 'integer'],
            [['maphieu', 'dienthoai', 'sohoadonVAT', 'sophieunhaptay'], 'string', 'max' => 45],
            [['diachi'], 'string', 'max' => 500],
//            [['nhacungcap_khachhang_id'], 'exist', 'skipOnError' => true, 'targetClass' => Nhacungcapkhachhang::className(), 'targetAttribute' => ['nhacungcap_khachhang_id' => 'id']],
            [['nhanviengiaodich'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['nhanviengiaodich' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'ngaygiaodich' => 'Ngaygiaodich',
            'nhacungcap_khachhang_id' => 'Nhacungcap Khachhang ID',
            'maphieu' => 'Maphieu',
            'dienthoai' => 'Dienthoai',
            'sohoadonVAT' => 'Sohoadon Vat',
            'sophieunhaptay' => 'Sophieunhaptay',
            'diachi' => 'Diachi',
            'ghichu' => 'Ghichu',
            'ngaygiao' => 'Ngaygiao',
            'kieuthanhtoan' => 'Kieuthanhtoan',
            'hinhthucthanhtoan' => 'Hinhthucthanhtoan',
            'hanthanhtoan' => 'Hanthanhtoan',
            'nhanviengiaodich' => 'Nhanviengiaodich',
            'chietkhau' => 'Chietkhau',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChitietmuabans()
    {
        return $this->hasMany(Chitietmuaban::className(), ['muabanhang_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNhacungcapKhachhang()
    {
        return $this->hasOne(Nhacungcapkhachhang::className(), ['id' => 'nhacungcap_khachhang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNhanviengiaodich0()
    {
        return $this->hasOne(User::className(), ['id' => 'nhanviengiaodich']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getThanhtoans()
    {
        return $this->hasMany(Thanhtoan::className(), ['muabanhang_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        if($this->ngaygiaodich != "")
            $this->ngaygiaodich = myFuncs::convertDateSaveIntoDb($this->ngaygiaodich);
        $this->nhacungcap_khachhang_id = myFuncs::getIdOtherModel($this->nhacungcap_khachhang_id, $nhacc = new Nhacungcapkhachhang(),'name',['name' => 'type', 'value' => 'nhacungcap']);
        $this->nhanviengiaodich = Yii::$app->user->getId();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

/*    public function afterSave($insert, $changedAttributes)
    {
        $tongtien = 0;
        foreach ($_POST['Chitietmuaban'] as $index => $item) {
            if(isset($item['quydoidonvitinh_id'])){
                $chitietMuaHang = new Chitietmuaban();
                $hanghoa = $_POST['Hanghoa'][$index];
                $donvitinh = $item['quydoidonvitinh_id'];

                $quydoidvt_id = Quydoidonvitinh::find()->where(['hanghoa_id' => $hanghoa, 'donvitinh_id' => $donvitinh])->one();
                $chitietMuaHang->quydoidonvitinh_id = $quydoidvt_id->id;
                $chitietMuaHang->muabanhang_id = $this->id;
                $chitietMuaHang->soluong = $item['soluong'];
                $chitietMuaHang->dongia = $item['dongia'];
                $chitietMuaHang->tongtien = $chitietMuaHang->dongia * $chitietMuaHang->soluong;
                if($this->type == 'mua')
                    $chitietMuaHang->thanhtien = $chitietMuaHang->tongtien;
                else
                    $chitietMuaHang->thanhtien = $chitietMuaHang->tongtien * $chitietMuaHang->chietkhau/100.0;
                $chitietMuaHang->save();
                $tongtien += $chitietMuaHang->thanhtien;

                // Lưu lại giá mua / bán
               // @TODO đang update
            }
        }
        Muabanhang::updateAll(['tongtien' => $tongtien, 'thanhtien' => $tongtien],['id' => $this->id]);
//        ();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }*/
}
