<?php

namespace backend\models;

use common\models\myFuncs;
use Yii;

/**
 * This is the model class for table "{{%quydoidonvitinh}}".
 *
 * @property integer $id
 * @property integer $hanghoa_id
 * @property integer $donvitinh_id
 * @property double $trongso
 * @property double $giamua
 * @property double $giaban
 *
 * @property Chitietmuaban[] $chitietmuabans
 * @property Khohanghoa[] $khohanghoas
 * @property Hanghoa $hanghoa
 * @property Donvitinh $donvitinh
 */
class Quydoidonvitinh extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%quydoidonvitinh}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hanghoa_id', 'donvitinh_id', 'trongso'], 'required', 'message' => 'Chưa nhập {attribute}'],
            [['hanghoa_id'], 'integer'],
            [['trongso'], 'number', 'min' => 1, 'tooSmall' => '{attribute} > = 1'],
            [['giamua', 'giaban'], 'number'],
            [['giamua', 'giaban'], 'safe'],
            [['hanghoa_id'], 'exist', 'skipOnError' => true, 'targetClass' => Hanghoa::className(), 'targetAttribute' => ['hanghoa_id' => 'id']],
//            [['donvitinh_id'], 'exist', 'skipOnError' => true, 'targetClass' => Donvitinh::className(), 'targetAttribute' => ['donvitinh_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'hanghoa_id' => 'Hàng hóa',
            'donvitinh_id' => 'Đơn vị tính',
            'trongso' => 'Trọng số',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChitietmuabans()
    {
        return $this->hasMany(Chitietmuaban::className(), ['quydoidonvitinh_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKhohanghoas()
    {
        return $this->hasMany(Khohanghoa::className(), ['quydoidonvitinh_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHanghoa()
    {
        return $this->hasOne(Hanghoa::className(), ['id' => 'hanghoa_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDonvitinh()
    {
        return $this->hasOne(Donvitinh::className(), ['id' => 'donvitinh_id']);
    }

    public function beforeSave($insert)
    {
        $this->donvitinh_id = myFuncs::getIdOtherModel($this->donvitinh_id, $dvt = new Donvitinh());

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        Chitietmuaban::deleteAll(['quydoidonvitinh_id' => $this->id]);
        Khohanghoa::deleteAll(['quydoidonvitinh_id' => $this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
