<?php

namespace backend\models;

use common\models\myFuncs;
use Yii;

/**
 * This is the model class for table "{{%hanghoa}}".
 *
 * @property integer $id
 * @property string $ma
 * @property string $name
 * @property integer $nhomloaihang_id
 * @property string $code
 * @property integer $donvitinh_id
 *
 * @property Chitietxuatnhapkho[] $chitietxuatnhapkhos
 * @property Nhomloaihang $nhomloaihang
 * @property Donvitinh $donvitinh
 * @property Tonkho[] $tonkhos
 */
class Hanghoa extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%hanghoa}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nhomloaihang_id', 'donvitinh_id','nhomloaihang_id'], 'required'],
            [['name','ma'], 'unique', 'on' => 'insert'],
//            [['nhomloaihang_id'], 'integer'],
            [['ma'], 'string', 'max' => 45],
            [['name', 'code'], 'string', 'max' => 100],
//            [['nhomloaihang_id'], 'exist', 'skipOnError' => true, 'targetClass' => Nhomloaihang::className(), 'targetAttribute' => ['nhomloaihang_id' => 'id']],
//            [['donvitinh_id'], 'exist', 'skipOnError' => true, 'targetClass' => Donvitinh::className(), 'targetAttribute' => ['donvitinh_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ma' => 'Mã hàng',
            'name' => 'Tên',
            'nhomloaihang_id' => 'Nhóm',
            'code' => 'Code',
            'donvitinh_id' => 'Đơn vị',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChitietxuatnhapkhos()
    {
        return $this->hasMany(Chitietxuatnhapkho::className(), ['hanghoa_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNhomloaihang()
    {
        return $this->hasOne(Nhomloaihang::className(), ['id' => 'nhomloaihang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDonvitinh()
    {
        return $this->hasOne(Donvitinh::className(), ['id' => 'donvitinh_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTonkhos()
    {
        return $this->hasMany(Tonkho::className(), ['hanghoa_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->donvitinh_id = myFuncs::getIdOtherModel($this->donvitinh_id, $dvt = new Donvitinh());
        $this->code = myFuncs::createCode($this->name);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
