<?php

namespace backend\models;

use common\models\myFuncs;
use Yii;

/**
 * This is the model class for table "{{%nhacungcap_khachhang}}".
 *
 * @property integer $id
 * @property string $ma
 * @property string $name
 * @property string $diachi
 * @property string $masothue
 * @property string $dtdoitac
 * @property string $dienthoai
 * @property string $tknganhang
 * @property string $nganhang
 * @property string $code
 * @property string $type
 * @property string $email
 * @property string $nguoilienhe
 * @property string $chucvu
 *
 * @property Hanghoa[] $hanghoas
 * @property Muabanhang[] $muabanhangs
 */
class Nhacungcapkhachhang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%nhacungcap_khachhang}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['type'], 'string'],
            [['ma', 'masothue', 'dtdoitac', 'dienthoai', 'tknganhang'], 'string', 'max' => 45],
            [['name', 'code', 'email', 'chucvu'], 'string', 'max' => 100],
            [['diachi'], 'string', 'max' => 400],
            [['nganhang'], 'string', 'max' => 500],
            [['nguoilienhe'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ma' => 'Mã',
            'name' => 'Tên',
            'diachi' => 'Địa chỉ',
            'masothue' => 'Mã số thuế',
            'dtdoitac' => 'ĐT đối tác',
            'dienthoai' => 'Điện thoại',
            'tknganhang' => 'TK Ngân hàng',
            'nganhang' => 'Ngân hàng',
            'code' => 'Code',
            'type' => 'Type',
            'email' => 'Email',
            'nguoilienhe' => 'Người liên hệ',
            'chucvu' => 'Chức vụ',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHanghoas()
    {
        return $this->hasMany(Hanghoa::className(), ['nhacungcap_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMuabanhangs()
    {
        return $this->hasMany(Muabanhang::className(), ['nhacungcap_khachhang_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->code = myFuncs::createCode($this->name);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
